import { defineArrayMember, defineField, defineType } from "sanity";
import { DocumentTextIcon } from "@sanity/icons/DocumentText";
import { TagIcon } from "@sanity/icons/Tag";
import { TagsIcon } from "@sanity/icons/Tags";
import { StackIcon } from "@sanity/icons/Stack";
import { UserIcon } from "@sanity/icons/User";
import { PlayIcon } from "@sanity/icons/Play";
import { MicrophoneIcon } from "@sanity/icons/Microphone";
import { RocketIcon } from "@sanity/icons/Rocket";
import { CaseIcon } from "@sanity/icons/Case";
import { LinkIcon } from "@sanity/icons/Link";
import { EnvelopeIcon } from "@sanity/icons/Envelope";

import { frenchRequired, languageField, localeSlugField, slugField } from "./shared";
import { FORMATS } from "../../lib/formats";

const hiddenWebflowId = defineField({
  name: "webflowId",
  title: "Webflow ID",
  type: "string",
  readOnly: true,
  hidden: ({ value }) => !value,
  description: "Set by the Webflow import. Used for re-imports and redirects.",
});

/* Set on English documents the import translated from French. Editors
   untick it once the translation has been reviewed. */
const machineTranslated = defineField({
  name: "machineTranslated",
  title: "Machine-translated",
  type: "boolean",
  description: "Translated automatically from the French. Untick once reviewed.",
  hidden: ({ value }) => !value,
});

export const articleType = defineType({
  name: "article",
  title: "Article",
  type: "document",
  icon: DocumentTextIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    slugField(),
    defineField({ name: "dek", title: "Summary", type: "text", rows: 3 }),
    defineField({ name: "image", title: "Main image", type: "figure" }),
    defineField({
      name: "category",
      title: "Section",
      description: "The rubrique the story is filed under. Leave empty for La Converse's own news.",
      type: "reference",
      to: [{ type: "category" }],
    }),
    defineField({
      name: "tags",
      title: "Topics",
      type: "array",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "tag" }],
        }),
      ],
    }),
    defineField({
      name: "authors",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "person" }] })],
    }),
    defineField({
      name: "format",
      type: "string",
      options: { list: FORMATS.map(({ value, fr, en }) => ({ value, title: `${fr} / ${en}` })) },
    }),
    defineField({
      name: "series",
      type: "reference",
      to: [{ type: "series" }],
    }),
    defineField({
      name: "photographers",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "person" }] })],
    }),
    defineField({
      name: "illustrators",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "person" }] })],
    }),
    defineField({
      name: "publishedAt",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
      validation: (r) => r.required(),
    }),
    defineField({
      name: "authorsNote",
      title: "Transparency box",
      description: "A note from the journalist on how the story came about.",
      type: "array",
      of: [
        defineArrayMember({
          type: "block",
          styles: [{ title: "Normal", value: "normal" }],
          lists: [],
          marks: {
            decorators: [
              { title: "Bold", value: "strong" },
              { title: "Italic", value: "em" },
            ],
            annotations: [
              defineArrayMember({
                name: "link",
                type: "object",
                fields: [defineField({ name: "href", type: "string" })],
              }),
            ],
          },
        }),
      ],
    }),
    defineField({ name: "trending", type: "boolean", initialValue: false }),
    defineField({
      name: "localJournalismInitiative",
      title: "Local Journalism Initiative",
      description: "Shows the LJI credit line on the article.",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "listen",
      title: "Audio version",
      type: "file",
      options: { accept: "audio/*" },
      description:
        "Shown as “Listen to the article”. Generated by `npm run tts`; upload a file here to use a human reading instead.",
    }),
    defineField({
      name: "listenSource",
      title: "Audio source hash",
      type: "string",
      readOnly: true,
      hidden: true,
      description: "Set by `npm run tts`: which version of the text the audio reads.",
    }),
    defineField({ name: "body", type: "richText" }),
    defineField({ name: "seo", type: "seo" }),
    machineTranslated,
    hiddenWebflowId,
  ],
  orderings: [
    { title: "Newest", name: "newest", by: [{ field: "publishedAt", direction: "desc" }] },
  ],
  preview: {
    select: { title: "title", media: "image", date: "publishedAt", lang: "language" },
    prepare: ({ title, media, date, lang }) => ({
      title,
      media,
      subtitle: [lang?.toUpperCase(), date?.slice(0, 10)].filter(Boolean).join(" · "),
    }),
  },
});

/* Sections, topics and series are one document for both languages: the
   title, slug and description each have a French and an English box. */
const taxonomyFields = [
  defineField({
    name: "title",
    type: "localeString",
    validation: (r) => r.custom(frenchRequired),
  }),
  localeSlugField(),
  defineField({ name: "description", type: "localeText" }),
];
const taxonomyPreview = {
  select: { fr: "title.fr", en: "title.en" },
  prepare: ({ fr, en }: { fr?: string; en?: string }) => ({
    title: fr ?? en,
    subtitle: en && en !== fr ? en : undefined,
  }),
};

/* Sections (rubriques): Société, Quartiers, Démocratie & pouvoir… */
export const categoryType = defineType({
  name: "category",
  title: "Section",
  type: "document",
  icon: TagIcon,
  fields: [
    ...taxonomyFields,
    defineField({
      name: "order",
      type: "number",
      description: "Position in the menu and filters.",
    }),
    hiddenWebflowId,
  ],
  preview: taxonomyPreview,
  orderings: [{ title: "Menu order", name: "order", by: [{ field: "order", direction: "asc" }] }],
});

/* Topics that cut across sections (Jeunesse, Racisme, Élections…). */
export const tagType = defineType({
  name: "tag",
  title: "Topic",
  type: "document",
  icon: TagsIcon,
  fields: [...taxonomyFields, hiddenWebflowId],
  preview: taxonomyPreview,
  orderings: [{ title: "Title", name: "title", by: [{ field: "title.fr", direction: "asc" }] }],
});

/* Recurring series: Hood Heroes, Dialogues, Lettres de La Converse… */
export const seriesType = defineType({
  name: "series",
  title: "Series",
  type: "document",
  icon: StackIcon,
  fields: taxonomyFields,
  preview: taxonomyPreview,
});

/* Journalists, team members and collaborators — one record per person, shared
   by both languages; only the role and bio are translated. */
export const personType = defineType({
  name: "person",
  title: "Person",
  type: "document",
  icon: UserIcon,
  fields: [
    defineField({ name: "name", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({ name: "image", title: "Portrait", type: "figure" }),
    defineField({ name: "role", type: "localeString" }),
    defineField({ name: "bio", type: "localeText" }),
    defineField({ name: "email", type: "string" }),
    defineField({
      name: "group",
      title: "Shown on the About page as",
      type: "string",
      options: {
        list: [
          { title: "Team", value: "team" },
          { title: "Collaborator", value: "collaborator" },
        ],
        layout: "radio",
      },
    }),
    defineField({ name: "order", type: "number" }),
    hiddenWebflowId,
  ],
  preview: { select: { title: "name", subtitle: "role.en", media: "image" } },
});

export const videoType = defineType({
  name: "video",
  title: "Video",
  type: "document",
  icon: PlayIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    slugField(),
    defineField({ name: "poster", type: "figure" }),
    defineField({
      name: "file",
      title: "Video file",
      type: "file",
      options: { accept: "video/*" },
    }),
    defineField({
      name: "videoUrl",
      title: "Or video URL",
      type: "url",
      description: "YouTube, Vimeo or a direct .mp4 link.",
    }),
    defineField({ name: "duration", title: "Duration (seconds)", type: "number" }),
    defineField({
      name: "category",
      title: "Section",
      type: "reference",
      to: [{ type: "category" }],
    }),
    defineField({ name: "series", type: "reference", to: [{ type: "series" }] }),
    defineField({
      name: "authors",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "person" }] })],
    }),
    defineField({
      name: "publishedAt",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
    }),
    defineField({ name: "body", type: "richText" }),
    defineField({ name: "seo", type: "seo" }),
    machineTranslated,
    hiddenWebflowId,
  ],
  orderings: [
    { title: "Newest", name: "newest", by: [{ field: "publishedAt", direction: "desc" }] },
  ],
});

export const podcastType = defineType({
  name: "podcast",
  title: "Podcast",
  type: "document",
  icon: MicrophoneIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    slugField(),
    defineField({ name: "cover", title: "Square cover", type: "figure" }),
    defineField({ name: "image", title: "Header photo", type: "figure" }),
    defineField({ name: "description", title: "Short description", type: "text", rows: 3 }),
    defineField({ name: "intro", type: "text", rows: 4 }),
    defineField({
      name: "episodes",
      type: "array",
      of: [
        defineArrayMember({
          name: "episode",
          type: "object",
          fields: [
            defineField({ name: "title", type: "string" }),
            defineField({ name: "description", type: "text", rows: 3 }),
            defineField({ name: "audio", type: "file", options: { accept: "audio/*" } }),
            defineField({ name: "audioUrl", title: "Or audio URL", type: "url" }),
            defineField({ name: "duration", title: "Duration (seconds)", type: "number" }),
            defineField({ name: "publishedAt", type: "date" }),
          ],
          preview: { select: { title: "title", subtitle: "publishedAt" } },
        }),
      ],
    }),
    defineField({
      name: "credits",
      type: "array",
      of: [
        defineArrayMember({
          name: "credit",
          type: "object",
          fields: [
            defineField({ name: "role", type: "string" }),
            defineField({ name: "names", type: "string" }),
          ],
          preview: { select: { title: "role", subtitle: "names" } },
        }),
      ],
    }),
    defineField({ name: "note", title: "Funding note", type: "text", rows: 2 }),
    defineField({ name: "order", type: "number" }),
    defineField({ name: "seo", type: "seo" }),
    machineTranslated,
    hiddenWebflowId,
  ],
});

/* La Relève programs: École Converse, MC Converse, Podcasts, Events… */
export const programType = defineType({
  name: "program",
  title: "Program",
  type: "document",
  icon: RocketIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    slugField(),
    defineField({ name: "image", type: "figure" }),
    defineField({
      name: "tagline",
      type: "text",
      rows: 2,
      description: "Bold line under the image.",
    }),
    defineField({ name: "body", type: "richText" }),
    defineField({ name: "cta", type: "cta" }),
    defineField({
      name: "quote",
      type: "object",
      fields: [
        defineField({ name: "image", type: "figure" }),
        defineField({ name: "text", type: "text", rows: 4 }),
        defineField({ name: "attribution", type: "string" }),
        defineField({ name: "source", type: "string" }),
      ],
    }),
    defineField({
      name: "form",
      title: "Sign-up form",
      type: "object",
      description: "Leave empty for no form.",
      fields: [
        defineField({ name: "title", type: "string" }),
        defineField({ name: "text", type: "text", rows: 2 }),
      ],
    }),
    defineField({
      name: "linkTo",
      title: "Card links to",
      type: "string",
      description: "Where the La Relève card goes. Defaults to this program's own page.",
      options: {
        list: [
          { title: "This program page", value: "self" },
          { title: "Podcasts index", value: "podcasts" },
        ],
        layout: "radio",
      },
      initialValue: "self",
    }),
    defineField({ name: "order", type: "number" }),
    defineField({ name: "seo", type: "seo" }),
  ],
});

export const positionType = defineType({
  name: "position",
  title: "Open position",
  type: "document",
  icon: CaseIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    slugField(),
    defineField({
      name: "meta",
      title: "Type · location",
      type: "string",
      description: "e.g. Full-time · Montréal",
    }),
    defineField({ name: "summary", type: "text", rows: 3 }),
    defineField({
      name: "responsibilities",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
    }),
    defineField({
      name: "profile",
      title: "Ideal profile",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
    }),
    defineField({ name: "open", type: "boolean", initialValue: true }),
    defineField({ name: "order", type: "number" }),
    machineTranslated,
  ],
});

/* Stories from partner outlets, shown in the Independent Media Portal rail. */
export const partnerStoryType = defineType({
  name: "partnerStory",
  title: "Partner story",
  type: "document",
  icon: LinkIcon,
  fields: [
    languageField,
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    defineField({ name: "url", title: "URL", type: "url", validation: (r) => r.required() }),
    defineField({ name: "image", type: "figure" }),
    defineField({ name: "partner", type: "string", title: "Outlet name" }),
    defineField({ name: "partnerLogo", type: "image" }),
    defineField({ name: "publishedAt", type: "date" }),
  ],
});

/* Inbox: voice notes, written stories, applications and contact messages sent
   from the site. Created by the API routes, never by hand. */
export const submissionType = defineType({
  name: "submission",
  title: "Submission",
  type: "document",
  icon: EnvelopeIcon,
  readOnly: ({ currentUser }) => !currentUser?.roles.some((r) => r.name === "administrator"),
  fields: [
    defineField({
      name: "kind",
      type: "string",
      options: {
        list: [
          { title: "Voice note", value: "voice" },
          { title: "Written story", value: "text" },
          { title: "Application", value: "application" },
          { title: "Program sign-up", value: "program" },
          { title: "Contact", value: "contact" },
        ],
      },
    }),
    defineField({
      name: "status",
      type: "string",
      options: { list: ["new", "read", "archived"], layout: "radio" },
      initialValue: "new",
      readOnly: false,
    }),
    defineField({ name: "audio", type: "file" }),
    defineField({ name: "cv", title: "CV", type: "file" }),
    defineField({ name: "message", type: "text" }),
    defineField({ name: "name", type: "string" }),
    defineField({ name: "email", type: "string" }),
    defineField({ name: "phone", type: "string" }),
    defineField({ name: "interests", type: "string" }),
    defineField({
      name: "context",
      type: "string",
      description: "Which form or position it came from.",
    }),
    defineField({ name: "language", type: "string" }),
    defineField({ name: "submittedAt", type: "datetime" }),
  ],
  orderings: [
    { title: "Newest", name: "newest", by: [{ field: "submittedAt", direction: "desc" }] },
  ],
  preview: {
    select: {
      kind: "kind",
      name: "name",
      context: "context",
      date: "submittedAt",
      status: "status",
    },
    prepare: ({ kind, name, context, date, status }) => ({
      title: `${status === "new" ? "● " : ""}${name || "Anonymous"}`,
      subtitle: [kind, context, date?.slice(0, 10)].filter(Boolean).join(" · "),
    }),
  },
});
